version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - 80:8080
    volumes:
      - ./app/uploads:/srv/www/photoapi/uploads
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/srv/www/photoapi
    expose:
      - 8000
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: api
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: